spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carshop?useUnicode=true&serverTimezone=UTC
    username: root
    password: 2281337UL
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: uniloft_database_create.sql